// Trigger registration. Two halves:
//   1. parseSchedule() — the human grammar in §2 -> 5-field cron (or passthrough)
//   2. harness adapters — actually register the recurring job on the target
// Every install also persists a local record under the state dir, so `list`
// and `update` work regardless of how the harness schedules.
import { mkdirSync, writeFileSync, readFileSync, existsSync, readdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { spawnSync } from "node:child_process";

export const STATE_DIR = join(homedir(), ".agenticloops", "loops");

const DOW = { sun: 0, mon: 1, tue: 2, wed: 3, thu: 4, fri: 5, sat: 6 };

// Human schedule grammar -> cron. Throws nothing; returns { cron } or { cron:null, raw }.
export function parseSchedule(input) {
  if (!input) return { cron: null, raw: input };
  const s = String(input).trim().toLowerCase();

  // Already a 5-field cron expression.
  if (/^[\d*/,\-?]+(\s+[\d*/,\-?a-z]+){4}$/.test(s)) return { cron: s };

  const at = s.match(/@\s*(\d{1,2}):(\d{2})/);
  const hh = at ? Number(at[1]) : 0;
  const mm = at ? Number(at[2]) : 0;

  let m;
  if ((m = s.match(/^every\s+(\d+)\s*h(ours?)?$/))) return { cron: `0 */${m[1]} * * *` };
  if ((m = s.match(/^every\s+(\d+)\s*m(in(utes?)?)?$/))) return { cron: `*/${m[1]} * * * *` };
  if (/^hourly$/.test(s)) return { cron: "0 * * * *" };
  if (/^daily/.test(s)) return { cron: `${mm} ${hh} * * *` };
  if (/^weekdays?/.test(s)) return { cron: `${mm} ${hh} * * 1-5` };
  if (/^weekly/.test(s)) return { cron: `${mm} ${hh} * * 0` };
  if ((m = s.match(/^(?:every\s+)?(sun|mon|tue|wed|thu|fri|sat)/))) {
    return { cron: `${mm} ${hh} * * ${DOW[m[1]]}` };
  }
  return { cron: null, raw: input };
}

export function recordPath(slug) {
  return join(STATE_DIR, slug);
}

// Persist the installed loop locally (the source of truth for list/update).
export function saveRecord(slug, data, raw) {
  const dir = recordPath(slug);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "LOOP.md"), raw, "utf8");
  writeFileSync(join(dir, "meta.json"), JSON.stringify(data, null, 2), "utf8");
}

export function listRecords() {
  if (!existsSync(STATE_DIR)) return [];
  return readdirSync(STATE_DIR)
    .map((slug) => {
      try {
        return JSON.parse(readFileSync(join(STATE_DIR, slug, "meta.json"), "utf8"));
      } catch {
        return null;
      }
    })
    .filter(Boolean);
}

export function removeRecord(slug) {
  const dir = recordPath(slug);
  if (existsSync(dir)) rmSync(dir, { recursive: true, force: true });
}

// --- harness adapters: register the recurring trigger -----------------------

function registerOn5dive({ name, prompt, cron, dryRun }) {
  const args = ["task", "add", name, "--body", prompt, "--recurring", cron];
  if (dryRun) return { ok: true, detail: `5dive ${args.join(" ")}`, skipped: "dry-run" };
  const res = spawnSync("5dive", args, { stdio: "inherit" });
  return { ok: res.status === 0, detail: `5dive ${args.join(" ")}`, status: res.status };
}

function registerGithubActions({ slug, name, cron, prompt, dryRun }) {
  const wf = join(process.cwd(), ".github", "workflows", `loop-${slug}.yml`);
  const yml = `# Generated by agenticloops — agentic loop "${name}"
name: loop-${slug}
on:
  schedule:
    - cron: "${cron}"
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # TODO: invoke your agent harness with the starter prompt below.
      # The prompt is committed at .agenticloops/${slug}.prompt.md
      - run: echo "run loop ${slug}"
`;
  if (dryRun) return { ok: true, detail: `write ${wf}`, skipped: "dry-run" };
  mkdirSync(join(process.cwd(), ".github", "workflows"), { recursive: true });
  writeFileSync(wf, yml, "utf8");
  mkdirSync(join(process.cwd(), ".agenticloops"), { recursive: true });
  writeFileSync(join(process.cwd(), ".agenticloops", `${slug}.prompt.md`), prompt, "utf8");
  return { ok: true, detail: `wrote ${wf}` };
}

// Generic cron: write a runner stub + the exact crontab line, but DON'T edit
// the user's crontab silently (invasive). The runner holds the starter prompt;
// the user drops in their harness's run command and installs the line.
function registerCron({ slug, name, prompt, cron, dryRun }) {
  const dir = recordPath(slug);
  const runner = join(dir, "run.sh");
  const line = `${cron} ${runner}  # agenticloops loop "${name}"`;
  if (dryRun) return { ok: true, scheduled: false, detail: `would scaffold ${runner} + crontab line` };
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    runner,
    `#!/usr/bin/env bash
# agenticloops runner for "${name}". Schedule: ${cron}
# The starter prompt is below. Replace the TODO with your harness's run command
# (e.g. \`claude -p\`, \`codex exec\`, or \`5dive agent send <agent>\`).
set -euo pipefail
PROMPT="$(cat "$(dirname "$0")/prompt.md")"
# TODO: pipe "$PROMPT" into your agent harness here.
echo "$PROMPT"
`,
    { mode: 0o755 },
  );
  writeFileSync(join(dir, "prompt.md"), prompt, "utf8");
  return {
    ok: true,
    scheduled: false,
    detail: `scaffolded ${runner} — add to crontab:  ${line}`,
  };
}

// For an interactive-only harness we record the loop but cannot honor the
// trigger; the caller has already warned. We still write the local record so
// the user can wire their own scheduler.
function registerLocalOnly({ slug }) {
  return {
    ok: true,
    detail: `recorded under ${recordPath(slug)} (no scheduler — wire cron or a scheduling harness)`,
    scheduled: false,
  };
}

export function registerTrigger(harnessId, ctx) {
  switch (harnessId) {
    case "5dive":
      return { scheduled: true, ...registerOn5dive(ctx) };
    case "github-actions":
      return { scheduled: true, ...registerGithubActions(ctx) };
    case "cron":
      return registerCron(ctx);
    default:
      return registerLocalOnly(ctx);
  }
}
